version: '3.4'

services:
  adb:
    image: 4c0n/adb:latest
    build:
      context: .
    volumes:
      - ./adb:/root/.android
    network: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 5037:5037

  rethinkdb:
    image: rethinkdb:2.4
    volumes:
      - ./data:/data:rw
    network: host

  openstf:
    image: 4c0n/stf:latest
    build:
      context: ./build/stf
    command: stf local
    depends_on:
      - adb
      - rethinkdb
    network: host
    ports:
      - 7100:7100
      - 7110:7110
      - 7400:7400
